### ISSUE TITLE
Added translator pages to site

### ISSUE THREAD

**Issue by natecook1000** [NSHipster/nshipster.com#27]
To go along with support for multiple authors on nshipster.cn, I've switched from having translator information as Jekyll "data" to a "collection", and have added individual pages for each translator with a bio. Please take a look and make sure your page looks okay—you can make changes and additions in the [_translators directory](https://github.com/NSHipster/nshipster.com/tree/master/nshipster.cn/_translators).

Thanks again for all your hard work!

**Comment by natecook1000** [comment]
@croath If you don't mind, could you check the subtitle on the author / translator pages? Should "Articles"  translate as "用品"? Also, I did my best with the listing of names in the footer, but am at sea with the grammar / what would be proper.

谢谢！

**Comment by croath** [comment]
Yep @natecook1000  I'd like to help here :)

Actually `Articles` should be translated to `文章` in Chinese.(Never believe in Google Translate if you're handling things with Chinese/Japanese/Korean lol)

And the current footer is absolutely correct right in grammar! It surprised me like the sentence is written by native speakers! Excellent job!

BTW if you have anything not that sure about Chinese, or anything you'd like it be translated into Chinese, just feel free to create an issue and give us a list, we'd deal with that!

**Comment by rickytan** [comment]
Look great!

**Comment by croath** [comment]
Looks great +1...
:clap: Thanks @natecook1000

**Comment by natecook1000** [comment]
Thanks all! :tada:
