### ISSUE TITLE
JSON Feed escapes HTML Tags

### ISSUE THREAD

**Issue by jbrayton** [NSHipster/nshipster.com#39]
The feed at https://nshipster.com/feed.json includes HTML that is escaped as if it was being served in an HTML or XML file. The result is that RSS readers show the raw HTML instead of formatted text.

I *think* the issue is this in the feed.json file:

`"content_html": {{ post.content | escape_once | jsonify }}`

I think escape_once should be removed.

**Comment by mattt** [comment]
Yikes. I'm sorry to hear that this hasn't been working for you, @jbrayton. Thanks for your patience on all of this. 

Unfortunately, `escape_once` was the only way I could get things to validate. The errors returned by the validator ("illegal character 311 on line 14") don't tell me much about what's wrong, and I have no idea how to fix it. I'm disappointed that escaped HTML isn't supported—especially given the challenges of encoding markup into valid JSON.

I've spent more time trying to get this to work than I can reasonably justify for something that few people are using and duplicates functionality already provided by an Atom / RSS feed. For now, the most reasonable solution seems to be removing it entirely (c0cda8dc).

If anyone is sufficiently motivated to get it working correctly, I'd be more than happy to reinstate it (PRs welcome!). But I'm not inclined to spend any more time on it myself.
