### ISSUE TITLE
nshipster.cn font issue

### ISSUE THREAD

**Issue by kylinroc** [NSHipster/nshipster.com#42]
nshipster.cn's font have some problem in desktop Safari:

<img width="616" alt="screen shot 2018-11-09 at 3 41 52 pm" src="https://user-images.githubusercontent.com/6008854/48249541-6776b580-e436-11e8-9c0c-93e484513d27.png">

But very good in mobile:

![img_6172](https://user-images.githubusercontent.com/6008854/48249586-8a08ce80-e436-11e8-965a-7a2b0e2a93e9.PNG)

Especially the أَلْف لَيْلَة وَلَيْلَة completely display wrong in desktop.

**Comment by mattt** [comment]
Very interesting! Thanks for pointing this out, @kylinroc.

I don't know what exactly was causing the problem, but wrapping the Arabic language text in a `span` element (https://github.com/NSHipster/articles-zh-Hans/commit/7ee3d596628ad68e21ef749511aedd4fd3b0fed7) appears to fix the display issue on the desktop:

<img width="933" alt="screen shot 2018-11-09 at 09 31 25" src="https://user-images.githubusercontent.com/7659/48278487-852a2780-e402-11e8-9f5c-e65319cfa1a4.png">

**Comment by mattt** [comment]
@kylinroc Are there any other typography issues that you would like to fix on desktop or mobile?

**Comment by kylinroc** [comment]
@mattt Actually I have one, but I think this one is not some thing can 'fix'. Currently the website use italic widely, but Chinese font don't have a real italic. In post I translated, I usually use bold over italic. (I think this maybe also an issue in Korean.)

**Comment by mattt** [comment]
Sounds good! Let's move this discussion over to #43.
