### ISSUE TITLE
Restyle Italic Text in Chinese and Korean Websites

### ISSUE THREAD

**Issue by mattt** [NSHipster/nshipster.com#43]
As described by @kylinroc in #42:

> Currently the website use italic widely, but Chinese font don't have a real italic. In post I translated, I usually use bold over italic. (I think this maybe also an issue in Korean.)

Currently, `<em>` and `<dfn>` are styled using italics. These styles should be overridden in CSS with a more specific language query.

**Comment by mattt** [comment]
Single and double emphasis in Markdown is translated into `<em>` and `<strong>` elements in HTML, respectively. These elements are semantic, and don't require italic or bold style (although that's usually the default).

@kylinroc What would be a better way to emphasize Chinese text? Bold? Underline? Highlight?

@pilgwon How about Korean text?

**Comment by kylinroc** [comment]
This issue should be separated to two part:

1. Website's static text
2. Post content's text

For 1, like "Continue Reading", "Recent Articles". I think the color and layout is enough for Chinese.

For 2, the general guideline is use bold over italic.

**Comment by pilgwon** [comment]
NSHipster.co.kr looks fine in Korean I think. (In Korean, we mainly use bold (strong) for emphasize something.)
After last korean font changing, NSHipster.co.kr's readability is good enough i think :)
So for now, there's nothing to change in korean.

**Comment by mattt** [comment]
Thanks for your feedback, @pilgwon.

If anyone finds any other issues going forward, please reopen this issue or let me know in some other way. 😄
