### ISSUE TITLE
CSS style `placeholder` difficult to read

### ISSUE THREAD

**Issue by Eitot** [NSHipster/nshipster.com#46]
From https://nshipster.com/apple-pay/:

<img width="911" alt="screenshot 2019-01-20 at 21 33 49" src="https://user-images.githubusercontent.com/15073177/51444694-5b8f5580-1cfb-11e9-989e-c6f3de6045c1.png">

**Comment by mattt** [comment]
Sorry about that, @Eitot. This is now fixed by 0d144fd742827b732a5250f6bad3c7c91cda1ff8.
